name: Run Terraform
 
on:
  push:
    branches:
      - main
  workflow_dispatch:
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
  AWS_REGION: "us-east-1"
  # CONFIGURE YOUR TERRAFORM CLOUD TOKEN
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN}}
      - name: Run Terraform Init
        run: terraform init
        working-directory: .
      - name: Run Terraform Plan
        run: terraform plan -var-file terraform.tfvars
        working-directory: .
      - name: Run Terraform Apply
        run: terraform apply -var-file terraform.tfvars -auto-approve
        working-directory: .
